#!/usr/bin/env python3
"""
Demo script showing the difference between test mode and real Claude API
"""

import os
import sys
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

from claude_api import ClaudeAPI

def demo_difference():
    """Demonstrate the difference between test mode and real API"""
    
    print("=" * 60)
    print("FANTASY STOCK MARKET GAME - API DEMO")
    print("=" * 60)
    
    # Check for API key
    has_api_key = bool(os.getenv("ANTHROPIC_API_KEY"))
    
    if has_api_key:
        print("Claude API Key: FOUND")
        print("Mode: REAL Claude API will be used")
        print("You will see:")
        print("- 75 unique companies generated by Claude AI")
        print("- Dynamic news based on current companies")
        print("- Real-time price calculations")
        print("- Personalized market analysis")
        print("- Creative company names and backstories")
    else:
        print("Claude API Key: NOT FOUND")
        print("Mode: FALLBACK (test mode) will be used")
        print("You will see:")
        print("- 75 predefined companies")
        print("- Generic news templates")
        print("- Simple price calculations")
        print("- Basic market analysis")
        print("- Static company data")
    
    print("\n" + "=" * 60)
    
    claude = ClaudeAPI()
    
    print("\n1. COMPANY GENERATION")
    print("-" * 30)
    
    if has_api_key:
        print("Calling Claude API to generate companies...")
        try:
            companies = claude.generate_companies()
            print(f"SUCCESS: Generated {len(companies)} companies")
            print("Example companies:")
            for i, company in enumerate(companies[:3], 1):
                print(f"  {i}. {company['symbol']}: {company['name']} ({company['sector']})")
                print(f"     {company['backstory']}")
        except Exception as e:
            print(f"API ERROR: {e}")
            print("Falling back to test mode...")
            companies = claude._generate_fallback_companies()
    else:
        print("Using fallback companies (test mode)...")
        companies = claude._generate_fallback_companies()
    
    print(f"\nTotal companies: {len(companies)}")
    
    print("\n2. NEWS GENERATION")
    print("-" * 30)
    
    game_state = {
        'companies': {c['symbol']: c for c in companies},
        'current_news': [],
        'special_events': []
    }
    
    if has_api_key:
        print("Calling Claude API to generate news...")
        try:
            news = claude.generate_market_news(game_state)
            print(f"SUCCESS: Generated {len(news)} news items")
            for i, news_item in enumerate(news, 1):
                print(f"  {i}. {news_item['headline']}")
        except Exception as e:
            print(f"API ERROR: {e}")
            print("Falling back to test mode...")
            news = claude._generate_fallback_news(list(game_state['companies'].keys()), 
                                                list(set(c['sector'] for c in companies.values())))
    else:
        print("Using fallback news (test mode)...")
        news = claude._generate_fallback_news(list(game_state['companies'].keys()), 
                                            list(set(c['sector'] for c in companies)))
    
    print(f"\nTotal news items: {len(news)}")
    
    print("\n3. MARKET RECAP")
    print("-" * 30)
    
    if has_api_key:
        print("Calling Claude API to generate market recap...")
        try:
            recap = claude.generate_market_recap(game_state)
            print("SUCCESS: Generated market recap")
            print(f"Recap length: {len(recap)} characters")
            print("Sample:", recap[:200] + "..." if len(recap) > 200 else recap)
        except Exception as e:
            print(f"API ERROR: {e}")
            print("Falling back to test mode...")
            recap = "MARKET RECAP: Another chaotic trading day comes to a close!"
    else:
        print("Using fallback recap (test mode)...")
        recap = "MARKET RECAP: Another chaotic trading day comes to a close!"
    
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    
    if has_api_key:
        print("To use REAL Claude API:")
        print("1. Set up your .env file with ANTHROPIC_API_KEY")
        print("2. Run: python gui_app.py")
        print("3. Enjoy dynamic, AI-generated content!")
    else:
        print("To use REAL Claude API:")
        print("1. Get an API key from https://console.anthropic.com")
        print("2. Create .env file with: ANTHROPIC_API_KEY=your_key_here")
        print("3. Run: python gui_app.py")
        print("4. Enjoy dynamic, AI-generated content!")
    
    print("\nFor now, you can play in test mode:")
    print("python gui_app.py --test")
    print("python main.py --test")

if __name__ == "__main__":
    demo_difference()
